# Generated by Django 3.0.5 on 2023-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20230828_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentTime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
